#!/bin/bash

input="$1"

if [[ "$1" == --compile ]]
then
    input="$2"
fi

if [[ "$input" == *.c ]]
then
    gcc -O2 -std=gnu11 -I../lib -I../res -march=native "$input" ../lib/ntc/*.c -lm -lgmp
elif [[ "$input" == *.cpp ]]
then
    clang++ -O2 -std=c++14 -I../lib -I../res -march=native "$input" -lm -lgmp -lgmpxx
else
    echo "Invalid input file"
    exit 1
fi

if [[ "$?" != 0 ]]
then
    exit 1
fi

if [[ "$1" != --compile ]]
then
    time ./a.out
    rm a.out
fi
